[patch.crates-io]
libmimalloc-sys = { git = "https://github.com/madsmtm/mimalloc_rust.git", branch = "true-override" }
tikv-jemalloc-sys = { git = "https://github.com/madsmtm/jemallocator.git", branch = "used-unprefixed" }
